### ISSUE TITLE
Issue with the makefile for PSI example

### ISSUE THREAD

**Issue by enedellec** [intel/confidential-computing-zoo#125]
Hi,

I tried to make the PSI example running in an Azure Cloud environment with Ubuntu 18.04, and with SGX enabled and running (e.g. Intel Architectural Enclave Service Manager is active).
I followed the instructions available here : [Private Set Intersection (PSI) with Intel SGX](https://cczoo.readthedocs.io/en/latest/Solutions/psi/PSI.html), but I am stuck at this stage :
```
cd CI-Examples/psi/python
./build.sh
```
I run into that issue with the python flavor of the example : 
```
+++ cp /grpc/src/dynamic_config.json /grpc/src/examples/python/psi/build
+++ python3 -m grpc_tools.protoc -I /grpc/src/examples/protos --python_out=/grpc/src/examples/python/psi/build --grpc_python_out=/grpc/src/examples/python/psi/build psi.proto
Makefile:21: /gramine/Scripts/Makefile.configs: No such file or directory
make: *** No rule to make target '/gramine/Scripts/Makefile.configs'.  Stop.
Usage: gramine-sgx-get-token [OPTIONS]

Error: Invalid value for "--sig" / "-s": Could not open file: python.sig: No such file or directory
Usage: gramine-sgx-get-token [OPTIONS]
```

Actually, the file `Makefile.configs` does not exist, and when I look at the git history, it is written that file, and that makefile are deprecated. It seems that PSI example is the only one which refers to the `Makefile.configs`  file.

Do you have any idea on how I could fix that?

Thank you!

**Comment by Hsy-Intel** [comment]
> Hi,
> 
> I tried to make the PSI example running in an Azure Cloud environment with Ubuntu 18.04, and with SGX enabled and running (e.g. Intel Architectural Enclave Service Manager is active). I followed the instructions available here : [Private Set Intersection (PSI) with Intel SGX](https://cczoo.readthedocs.io/en/latest/Solutions/psi/PSI.html), but I am stuck at this stage :
> 
> ```
> cd CI-Examples/psi/python
> ./build.sh
> ```
> 
> I run into that issue with the python flavor of the example :
> 
> ```
> +++ cp /grpc/src/dynamic_config.json /grpc/src/examples/python/psi/build
> +++ python3 -m grpc_tools.protoc -I /grpc/src/examples/protos --python_out=/grpc/src/examples/python/psi/build --grpc_python_out=/grpc/src/examples/python/psi/build psi.proto
> Makefile:21: /gramine/Scripts/Makefile.configs: No such file or directory
> make: *** No rule to make target '/gramine/Scripts/Makefile.configs'.  Stop.
> Usage: gramine-sgx-get-token [OPTIONS]
> 
> Error: Invalid value for "--sig" / "-s": Could not open file: python.sig: No such file or directory
> Usage: gramine-sgx-get-token [OPTIONS]
> ```
> 
> Actually, the file `Makefile.configs` does not exist, and when I look at the git history, it is written that file, and that makefile are deprecated. It seems that PSI example is the only one which refers to the `Makefile.configs` file.
> 
> Do you have any idea on how I could fix that?
> 
> Thank you!


Hi enedellec,

The error is that the Gramine version on the `main` branch is higher (v 1.2), and the PSI solution has not upgraded the Gramine yet.

The error can be solved by switching the branch to `branch-dev/psi` and recompiling the Gramine docker image.

We will then upgrade the Gramine version in the PSI solution to run on the `main` branch.

Thanks for your question.

**Comment by enedellec** [comment]
Thank you for your prompt reply, I will try that.

**Comment by RodgerZhu** [comment]
Close this issue.
