### ISSUE TITLE
Where is key.example in tdx-encrypted-tdvm-image 

### ISSUE THREAD

**Issue by GeminiCarrie** [intel/confidential-computing-zoo#249]
When executing this script tdx-encrypted-tdvm-image/initramfs-hooks/ubuntu/hook-add-executables, an error message is returned

![image](https://github.com/intel/confidential-computing-zoo/assets/53326210/b4751b8a-bde3-41c2-8f29-5a54150b7442)

**Comment by RodgerZhu** [comment]
> When executing this script tdx-encrypted-tdvm-image/initramfs-hooks/ubuntu/hook-add-executables, an error message is returned
> 
> ![image](https://user-images.githubusercontent.com/53326210/270947473-b4751b8a-bde3-41c2-8f29-5a54150b7442.png)

Hi @GeminiCarrie , please just remove this line. It's used for local debugging. 
If you don't want to use remote attestation to fetch the key, you can first use a local key file to debug the flow.
