### ISSUE TITLE
ra-tls-grpc

### ISSUE THREAD

**Issue by reclock** [intel/confidential-computing-zoo#265]
When I start the GRPC server, the following error occurs：

E0104 11:17:52.048905000       1 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1704367072.048218000","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":202,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
[P1:T1:python3.8] error: bind: invalid handle returned

Do you know if this error will affect the establishment of the GRPC network

**Comment by 0400H** [comment]
> E0104 11:17:52.048905000 1 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1704367072.048218000","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":202,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
> [P1:T1:python3.8] error: bind: invalid handle returned


Run with gramine?
Perhaps the server is running twice on the same port, and gramine does not support "SO_REUSEPORT".

Check this [Link](https://github.com/gramineproject/gramine/issues/763) for detail.

**Comment by RodgerZhu** [comment]
No comment.
