### ISSUE TITLE
tdx-encrypted-tdvm-image.md typing error

### ISSUE THREAD

**Issue by kunshen1** [intel/confidential-computing-zoo#269]
https://github.com/intel/confidential-computing-zoo/tree/main/cczoo/tdx-encrypted-tdvm-image
There is a typing error
![image](https://github.com/intel/confidential-computing-zoo/assets/54119762/a3114374-a8d9-4bae-8579-cb6481a5e7a1)

**Comment by RodgerZhu** [comment]
> https://github.com/intel/confidential-computing-zoo/tree/main/cczoo/tdx-encrypted-tdvm-image There is a typing error ![image](https://private-user-images.githubusercontent.com/54119762/298815673-a3114374-a8d9-4bae-8579-cb6481a5e7a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTEyODcsIm5iZiI6MTcwODMxMDk4NywicGF0aCI6Ii81NDExOTc2Mi8yOTg4MTU2NzMtYTMxMTQzNzQtYThkOS00YmFlLTg1NzktY2I2NDgxYTVlN2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyNDk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhODYwODhiOTk5NjAxOWI5M2M0YTU3OGIzMDE1Zjg1NGRmNGJjMmRkNWFmYzliNDA5NzA2NzFiNzA3OGQwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hH2V2ClJN7uTk7b7BHHoZyma2A08Nt-JlEXVva957QI)

Thanks Kun for the comment. 
Fixed.
