### ISSUE TITLE
hurry

### ISSUE THREAD

**Issue by huiyuchen708** [intel/confidential-computing-zoo#286]
Why does "server.py" need to read the "rag.yaml" file, but I haven't found this file in the project, do I need to write it myself?

**Comment by Hsy-Intel** [comment]
I have updated the code, please see #285, thanks.

**Comment by huiyuchen708** [comment]
![Snipaste_2024-10-22_21-42-05](https://github.com/user-attachments/assets/3d9590e2-bc90-45ce-a6d0-09e6ea2c1c39)
How can we solve this problem
